# Use root/example as user/password credentials
version: '3.7'
services:
  mongodb_container:
    name: mongodb-salo
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/home/salomo/docker-volumenes/datamongo/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: salome
      MONGO_INITDB_ROOT_PASSWORD: 0000

volumes:
  mongodb_data_container: